Core/src/main/java/com/darwinreforged/server/core/commands/CommandBus.java, Core/src/main/java/com/darwinreforged/server/core/commands/annotations/Permission.java, Core/src/main/java/com/darwinreforged/server/core/commands/registrations/ClassRegistration.java, Core/src/main/java/com/darwinreforged/server/core/commands/registrations/CommandRegistration.java, Core/src/main/java/com/darwinreforged/server/core/commands/registrations/SingleMethodRegistration.java, Core/src/main/java/com/darwinreforged/server/modules/oldplot/OldPlotModule.java
Currently only primary aliases indicated in `context` are being registered. To fix this the context is now updated for each present alias, therefore creating a custom context for each alias. This also affects sub-commands, so e.g. parent command `/tp` and `/teleport` with sub-command `player` and `p` would result in the following contexts : 
- `/tp p`
- `/tp player`
- `/teleport p`
- `/teleport player`
=> Fix secondary aliases not registering

hartshorn-sponge-8/src/main/java/org/dockbox/hartshorn/sponge/Sponge8Application.java
Updates the import for `@Plugin` as [plugin-spi](https://github.com/SpongePowered/plugin-spi) (a dependency of [Sponge](https://github.com/SpongePowered/Sponge)) recently updates its location, causing our builds to fail.
=> Update Sponge application plugin-spi

README.md
While `@ExtendWith(HartshornRunner.class)` still works, the recommended workflow is to extend `ApplicationAwareTest` which provides better control over the active context. This PR updates the README to follow this workflow.
=> Update embedded server documentation to use `ApplicationAwareTest`

hartshorn-di/src/impl/java/org/dockbox/hartshorn/di/TypeFactoryImpl.java, hartshorn-di/src/impl/java/org/dockbox/hartshorn/di/context/HartshornApplicationContext.java, hartshorn-di/src/main/java/org/dockbox/hartshorn/di/context/ApplicationBinder.java, hartshorn-di/src/main/java/org/dockbox/hartshorn/di/context/element/WildcardTypeContext.java, hartshorn-di/src/main/java/org/dockbox/hartshorn/di/inject/Binder.java, hartshorn-di/src/main/java/org/dockbox/hartshorn/di/inject/DelegatedBinder.java, hartshorn-di/src/test/java/org/dockbox/hartshorn/di/ApplicationContextTests.java, hartshorn-di/src/test/java/org/dockbox/hartshorn/di/BindingHierarchyTests.java, hartshorn-di/src/test/java/test/types/dual/DualConstructableType.java, hartshorn-minecraft/hotbar/src/main/java/org/dockbox/hartshorn/hotbar/HotbarService.java, hartshorn-sponge-8/src/main/java/org/dockbox/hartshorn/sponge/inject/SpongeInjector.java, hartshorn-test/src/testFixtures/java/org/dockbox/hartshorn/test/util/JUnitInjector.java
Fixes #357 
Currently it's not possible to use `Binder.bind` for both static bindings and bound bindings. This is a remnant of the Guice implementations, as there was a need to separate this functionality.
Removes `Binder.manual` which was previously responsible for bound constructors. Types with constructors supporting bound injection are now automatically picked up by `Binder.bind`. `.bind` will create dual bindings if the type supports both bound and injected construction.
Additionally, `Binder.provide` was renamed to `Binder.bind` to make all binding related methods be consistent with each other.
`ApplicationBinder.firstWire` now accepts a `Key` rather than a separate `TypeContext` and `Named` instance.
* Java version: 16.0.1
=> #357 Rework Binder.manual into Binder.bind

hartshorn-di/src/main/java/org/dockbox/hartshorn/di/context/element/TypeContext.java
Fixes #389 
`TypeContext` previously assumed that the requested type is a 'real' (non-proxied) type. This allowed for the potential issue that a proxy type is used to request metadata. This would lead to (e.g.) empty method collections, as the real type is never inspected.
As this is considered a developer fault, as `TypeContext.unproxy` should be used when reflecting methods and fields, the solution to this issue is to validate the availability of metadata before requesting it. In this context that means the validation verifies the type is _not_ a proxied type. If it is, a runtime `ApplicationException` is thrown.
=> #389 Verify metadata availability in TypeContext

.github/workflows/owasp.yml, build.gradle
Fixes #394
Recently it was noticed that dependencies like Guava have been outdated for a expanded amount of time. The used version was 21.0, while the latest was 30.1.1.
A new Gradle plugin has been added, [dependency check Gradle](https://github.com/dependency-check/dependency-check-gradle). This task is added to a new GitHub Actions workflow, so dependencies are (strictly) checked before a PR can be merged.
=> #394 Gradle dependency analysis and workflow

build.gradle, hartshorn-commands/src/impl/java/org/dockbox/hartshorn/commands/service/CommandParameterValidator.java, hartshorn-commands/src/impl/java/org/dockbox/hartshorn/commands/service/CommandServiceScanner.java, hartshorn-di/src/main/java/org/dockbox/hartshorn/di/context/element/TypeContext.java
Affects #355
- Parameter names are now kept when compiling test sources
- A warning will be shown during early evaluation if parameter names are obfuscated
* Java version: 16.0.1
=> #355 Minor issues

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/service/ServiceActivator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Fixes #452 
By default two packages are scanned when an application is bootstrapped; `org.dockbox.hartshorn` and the package in which the application activator is located. This works fine while modules are only in Hartshorn itself, but lacks support for third-party modules.  
For example, if I create an application in `com.example.myapp`, and want to use services provided by a third party which are located in `net.thirdparty.services`, their package will not be scanned unless I manually define it.
`@ServiceActivator` now has an optional attribute `scanPackages` which indicates the packages to be added to the environment context. As the environment already filters out duplicates this is a non-concern from the aspect of the application context.
* Java version: …
=> #452 Add `scanPackages` to `@ServiceActivator`

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/SystemSubject.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/arguments/DefaultArgumentConverters.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/ResourceService.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/ResourceServiceImpl.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/common/DefinedLanguage.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/common/Language.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/common/Languages.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/common/PersistentLanguageModel.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/message/DetachedMessage.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/message/MessageTemplate.java, hartshorn-i18n/src/test/java/org/dockbox/hartshorn/i18n/MessageTemplateServiceTests.java
Fixes #450
Currently the `Language` definition in the [Language](https://github.com/GuusLieben/Hartshorn/blob/566beff8656ddcb59967e2883a090465c4621453/hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/common/Language.java) enum is entirely static, with no option for developers to extend this with their own languages or dialects.  
Separates the `Language` enum into a reusable `Language` interface and renamed the enum to `Languages`. Usages have been updated accordingly.  
This PR is in preparation of #449.
=> #450 Restructure `Language` definitions into separate contract

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Fixes #466
When annotating a field as follows, only the type is used to construct a `Key` referencing the hierarchy (see `HartshornApplicationContext#L497`)
https://github.com/GuusLieben/Hartshorn/blob/c635bee574db25db465c1803f9608194186e4a83/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L497
```java
public class SimpleInjectableBean {
@Inject
@Named("bean_target")
private OtherBean other;
}
```
This leads to the key: `Key<OtherBean>` rather than the expected `Key<OtherBean, bean_target>`.
Reimplement support for `@Named`. This should be followed up later with dynamic field processing rules so `@Inject` and `@Context` support is not hardcoded.
=> #466 Include `@Named` when constructing hierarchy `Key`s inside `HartshornApplicationContext`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/Enable.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/binding/Bindings.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/properties/Attribute.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/properties/AttributeHolder.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/properties/AttributeImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/properties/Enableable.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/properties/UseFactory.java
Fixes #472
`Attribute`s, and the associated `AttributeHolder` remain as a obscure part of Hartshorn. It allows for unchecked actions, and can fail hard if an implementation decides information is strictly required. As the current factory construction of types depends on attributes, I proposed #473 as a potential solution to its removal.
Do note that `AttributeHolder` also defines `enable()`, this method has been moved to `Enableable`. Deprecation descriptions link to the new interface and `Bindings.enable` has been updated accordingly.
=> #472 Deprecate `Attribute` and `AttributeHolder` for removal

hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletHandler.java
Fixes #468
When returning a string value through a `RestController` service, the underlying `ServletHandler` correctly skips object mapping and directly writes the result to the response writer. However it always sets the content type to `application/json`.  
This leads to potential incorrect handling of the returned values. For example Rest clients like Insomnia assume spaces are invalid in visual previews, and thus the message `Hello world` becomes `Helloworld`.  
Additionally, when the object _is_ mapped, the content type is always `application/json`, even if the value is mapped to e.g. xml.
https://github.com/GuusLieben/Hartshorn/blob/c635bee574db25db465c1803f9608194186e4a83/hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletHandler.java#L96
The content type is now …
=> #468 Resolve incorrect `application/json` content-type, will now resolve based on mapping format or write as `text/plain`

hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheEvictionMethodModifier.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheServiceModifier.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheUpdateMethodModifier.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CachedMethodModifier.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/service/ArgumentServiceProcessor.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/service/CommandParameters.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/service/CommandServiceScanner.java, hartshorn-config/src/main/java/org/dockbox/hartshorn/config/ConfigurationServiceModifier.java, hartshorn-config/src/main/java/org/dockbox/hartshorn/config/ConfigurationServiceProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/service/AutomaticActivation.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContextInjectionProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ContextCarrierDelegationModifier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ContextMethodModifier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/DelegatorAccessorDelegationModifier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServiceModifier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServiceProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/LifecycleObserverProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ProviderServiceProcessor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/DemoProxyDelegationModifier.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventServiceProcessor.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/services/LanguageProviderServiceProcessor.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/services/TranslationInjectModifier.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/service/DeserialisationServiceModifier.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/service/JpaRepositoryDelegationModifier.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/service/QueryModifier.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/service/SerialisationServiceModifier.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/RestControllerProcessor.java
Fixes #490
Currently all component- processors and modifiers are automatically activated when their activator is present. However in some cases it may be preferred to activate these handlers manually and/or programmatically.
Adds a new way of marking automatically active processors and modifiers, annotating them with `@AutomaticActivation`. `HartshornApplicationContext#lookupActivatables()` will filter for this annotation on lookup, and will only register automatically active processors and modifiers.  
Additionally, it is now possible to register processors and modifiers through a `ApplicationFactory`, without the need of their official activator.
* Java version: Corretto 16.0.2
=> #490 Automatic activation of component- processors and modifiers

hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/RequestParam.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/processing/HttpServletParameterLoader.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/processing/rules/BodyRequestParameterRule.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/processing/rules/RequestQueryParameterRule.java
Fixes #496
Currently it is not possible to provide query parameters to request handles, e.g. the parameter `name` in `http://localhost:8080/greeting?name=Guus` cannot be obtained without accessing the `HttpServletRequest` directly.
Adds a `@RequestParam` annotation which can be used to populate servlet handle arguments. When a parameter is annotated with `@RequestParam` the value will be looked up through `HttpServletRequest#getParameter`. If the parameter type is primitive it is automatically mapped to the correct primitive value.
* Platform: REST using Insomnia
=> #496 Add `@RequestParam` rule support to read query parameters from `HttpServletRequest` when populating servlet handle arguments

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/AnnotationHelper.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java
Fixes #497 
> Concrete case; `@RestController` extends from `@Service`, which extends from `@Component`. `@Service` changes the default value for `singleton()` from false to true. When `@Service` itself is requested, the value of `singleton()` is true, however when `@RestControlelr` is requested, the value of `singleton()` is false.  
> I observed that annotating `@RestController` with a default `@Service` will fix this, as well as annotating `@Service` with `@Component(singleton=true)`. While both of these solutions technically work, they are simply bypassing the greater issue. `AnnotationHelper` does not check the potential default value of a attribute after checking `AliasFor`, and before checking the top annotations (`@Component` on `@Service`). This should thus be resolvable by …
=> #497 Include default values when looking up annotation attribute hierarchy

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/cli/SimpleCommandCLI.java
Fixes #494
Moves the creation of the `Scanner` object into the (potentially) async runnable.
=> #494 Resolve asynchronous access to thread-locked Scanner object in CommandCLI

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/service/CommandParameterValidator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/LifecycleObserver.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventValidator.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/service/PersistentTypeService.java
Fixes #516
It's currently not possible to listen for application exits, besides manually registering shutdown hooks through `Runtime.getRuntime().addShutdownHook(Thread)`. To resolve this it is now possible for `LifecycleObserver`s to listen to application exits, to allow them to clean up before exiting.
=> #516 Add `onExit` state observable

hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServer.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServerBootstrap.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyDirectoryServlet.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyHttpWebServer.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyResourceService.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/servlet/DirectoryServlet.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/servlet/HttpWebServletAdapter.java
Fixes #512
Serving static content through the web module allows users of future MVC support ( #509 ) to use resources like CSS and JavaScript directly, rather than having to hardcode it or depending on a secondary DNS.  
This PR adds a configuration to the `HttpWebServer` which can then serve all content in `/WEB-INF/static/` according to the directory structure in that directory. If no content is found, the servlet will attempt to list the directory contents if it exists, this behavior can be customized through the implementation of `DirectoryServlet`.  
As this implementation, as well as the MVC implementation, has shown that there will be more generic `javax.servlet.Servlet`s I have modified the `#register` method in the `HttpWebServer` to support registering a generic `Servlet` with a …
=> #512 Allow serving static content through `HttpWebServer`

examples/src/persistence/java/org/dockbox/hartshorn/demo/persistence/services/UserRepository.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/hibernate/HibernateJpaRepository.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/jpa/JpaRepository.java
Fixes #519
Convenience feature, directly returns the saved or updated entity through `JpaRepository` for all save/update actions.
=> #519 Return persisted entity when updating or saving through `JpaRepository`

hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/hibernate/HibernateJpaRepository.java
Fixes #520 
> When a session is requested in the `HibernateJpaRepository` while no active session exists, the session is created using the connection present in the repository. However the presence of the connection is not validated. This causes `HibernateJpaRepository#session` to throw an NPE when `connection().url()` is requested.
The connection will now be validated beforehand, if the connection is absent an exception is thrown before a session can be created.
=> #520 Validate `PersistenceConnection` before opening session in `HibernateJpaRepository`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/AnnotatedElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java
Fixes #531
When comparing `MethodContext` on two separately obtained methods with the same signature, the direct comparison will return `false`. However when comparing the real `Method`, the result is `true`. This is because the `MethodContext` does not have a explicit `equals` and `hashCode` override.
`AnnotatedElementContext` now defines a explicit override for `equals` and `hashCode`, which affects the following contexts directly:
- `ConstructorContext`
- `FieldContext`
- `MethodContext`
- `ParameterContext`
- `TypeContext`
- `WildcardTypeContext`
=> #531 Add `#equals` to `AnnotatedElementContext` to compare underlying reflected element directly for all contexts

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java
Fixes #532
While inherited `private` methods should not be accessible through `TypeContext#methods`, protected should be accessible so they can be proxied when needed. Currently protected methods are not always properly included.
Updates the implementation of `methods` to recursively obtain all methods which are then filtered by their access modifier (public and protected only). Also adds a separate `declaredMethods` method to obtain all type-declared methods.
=> #532 Include inherited protected methods in `TypeContext#methods`, keep `#declaredMethods` for type-declared methods

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/AnnotatedElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java
Fixes #535
When validating annotations, both the `TypeContext` and `AnnotatedElementContext` use the class of present annotation instances. However annotation instances are typically proxies and are thus not correctly compared. This can lead to duplication in the annotation cache.
Replaces the use of `annotation.getClass` in annotation cache builders with `annotation.annotationType`.
=> #535 Use annotation type instead of instance class for annotation cache

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/AnnotatedElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ExecutableElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypedElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Named.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ElementContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/AbstractTypeWithTP.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/AnnotatedElement.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/ImplementationWithTP.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/InterfaceWithTP.java
Fixes #529
Includes tests for #534 and #536 
> There's no way to get the name from an `ExecutableElementContext<?>` without casting to either a `MethodContext<?,?>` or `ConstructorContext<?>`, despite this being a method of the built-in `Executable`. It may not be known which of these it is and therefore just to get the name, several lines of code must be written.
To make it easier in the future to handle named types, I also added a separate `Named` interface which exposes only the method `String name()`.
This is primarily a QoL change, allowing you to get a annotation from a `AnnotatedElementContext` directly using a `TypeContext` which may represent an annotation type. I also included a quick bypass for requests using types (both `Class` and `TypeContext`) which don't represent an …
=> #529 QoL changes to `TypeContext` and associated contexts

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Fixes #541
When processing a new prefix, `HartshornApplicationContext` checks all components for activator presence. While this is technically correct, it does not fall within the scope of the application context, and is instead already handled by the `ComponentLocator` implementation. See the line below for refence:  
https://github.com/GuusLieben/Hartshorn/blob/6e7b2caa5a8d75a91e85b5dfb2bd55611febab80/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L256
=> #541 Remove duplicate activator check for processed components

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/SingletonEnableable.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/TypeWithEnabledInjectField.java
Fixes #540
> When a field is annotated with `@Inject` as well as `@Enable`, it is injected and enabled in the `enableFields` method in `HartshornApplicationContext`, see: https://github.com/GuusLieben/Hartshorn/blob/6e7b2caa5a8d75a91e85b5dfb2bd55611febab80/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L171  
> 
> However, two lines above that the fields are already enabled as they are annotated with `@Enable`, see https://github.com/GuusLieben/Hartshorn/blob/6e7b2caa5a8d75a91e85b5dfb2bd55611febab80/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L168  
> 
> Even more so, the fields are already populated through `HartshornApplicationContext#populate`, see …
=> #540 Resolve duplicate field injection when field is annotated with both `@Inject` and `@Enable`

hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java, hartshorn-web/src/test/java/org/dockbox/hartshorn/web/RestIntegrationTest.java
Fixes #537
> The `ServerBootstrap` used to activate the `HttpWebServer` (sidenote, `ServerBootstrap` needs to be renamed asap, it's too ambiguous), requires the activator `UseBootstrap` instead of `UseHttpServer`. See:  
https://github.com/GuusLieben/Hartshorn/blob/6e7b2caa5a8d75a91e85b5dfb2bd55611febab80/hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServerBootstrap.java#L42
Changes the activator for the `HttpWebServerInitializer` (previously `ServerBootstrap`) to `UseHttpServer` with additional checks for the presence of `UseMvcServer` before registering MVC servlets.
* Platform: Jetty Embedded
=> #537 Use correct activator for `HttpWebServerInitializer` and specify presence of MVC activator for MVC servlets

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/exceptions/ApplicationException.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletHandler.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyErrorHandler.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyHttpWebServer.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyServer.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/servlet/HttpWebServletAdapter.java
Fixes #522
> When an exception is thrown inside a servlet handler, the exception is ignored. This causes the application to immediately fall back to default behavior, which typically is returning SC405 (method not supported).
Will now correctly pass exceptions when handling servlets. If an exception is thrown it is rethrown so Jetty can handle it appropriately (this will pass it into the configured `ErrorServlet` so you keep control of everything). If no response was given, and no exception was thrown the status code `204` (No content) is returned instead of falling back to `405` (Method not supported)
=> #522 Correctly pass exceptions when handling servlets

hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/annotations/Query.java
Fixes #528
> `@Query` defines the property `autoFlush`, currently this defaults to `false`. However this can quickly lead to memory leaks and unexpected behavior on multithreaded applications.
=> #528 Change default flush mode to always be active for `@Query` methods

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/service/CommandParameterValidator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/LifecycleObserver.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/JavaInterfaceProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/NativeProxyLookup.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/ProxyLookup.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyLookup.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyUtil.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventValidator.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/hibernate/HibernateProxyLookup.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/hibernate/HibernateProxyLookupInitializer.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/service/PersistentTypeService.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java
Fixes #527
> Explicit support was already added to support proxies generated by Java (native interface proxies), Javassist, and interface proxies. However support for Hibernate proxies is still lacking. While this is currently not required internally, this does not mean it won't be needed elsewhere.
As Core doesn't have access to Hibernate, we needed an alternative method of efficiently getting proxy context for Hibernate proxies. To support this, I have added a new way of validating proxy types; `ProxyLookup`. This is implemented in the `HartshornApplicationProxier` so additional lookups can be registered through lifecycle observers or during processing.  
The `ProxyLookup` supports two things:
- Getting the real unproxied class of a provided instance
- Validating whether a given …
=> #527 Add support for Hibernate proxies

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/binding/ContextDrivenProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/logback/LogbackEncoder.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/logback/LogbackPIDConverter.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ConstructorContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Named.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/exceptions/BeanProvisionException.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/NativeProxyLookup.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/ProxyLookup.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyLookup.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ElementContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/AbstractTypeWithTP.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/AnnotatedElement.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/ComponentType.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/ImplementationWithTP.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/InterfaceWithTP.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/NonComponentType.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/SingletonEnableable.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/TypeWithEnabledInjectField.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/TypeWithFailingConstructor.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/hibernate/HibernateProxyLookup.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/hibernate/HibernateProxyLookupInitializer.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyServer.java
Fixes #542
> Currently all provided types follow three main steps when being created:
> 1. Attempt to create through provider(s) if present
> 2. Attempt to create raw instance through constructor injection
> 3. Attempt to create proxy instance
> 
> This order makes sense for almost all types, except for step 3. Empty proxies should only ever be created for types which can later be modified to carry method handlers. These types are always components, as modifiers cannot target other types. Thus, step 3 should never be applied to non-components.  
> 
> Additionally, exceptions in step 1 are ignored unless an additional exception is thrown in step 2. This should be deferred since the introduction of `Provider`s, as providers should be able to yield an exception. If a provider cannot supply …
=> #542 Defer instance proxies for non-components and resolve lost exceptions through type provisions

hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/DefaultObjectMapper.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/jackson/JacksonObjectMapper.java, hartshorn-persistence/src/main/java/org/dockbox/hartshorn/persistence/mapping/ObjectMapper.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/MediaType.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletHandler.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/http/HttpDelete.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/http/HttpGet.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/http/HttpPost.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/http/HttpPut.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/http/HttpRequest.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/processing/rules/BodyRequestParameterRule.java, hartshorn-web/src/test/java/org/dockbox/hartshorn/web/RequestArgumentProcessorTests.java
Fixes #555
- Adds a new `MediaType` enum which defines information about the associated `type`, `subtype`, and optional `FileFormat`
- Renames `responseFormat` and `bodyFormat` in `HttpRequest` (and derivatives) to `produces` and `consumes`, respectively
- Matches the response content type header with the intended `MediaType`
=> #555 Media type enhancements for HTTP request mappings

hartshorn-config/src/main/java/org/dockbox/hartshorn/config/ConfigurationServiceProcessor.java
Fixes #562
The `ConfigurationServiceProcessor` allows us to define custom `ResourceLookupStrategy` instances. However, these are currently stored in a static field. This causes the strategies to be shared across global states, while these may only be expected to be present in specific states.
https://github.com/GuusLieben/Hartshorn/blob/f27f21c255ef44a408b131b5298819db3ec543fd/hartshorn-config/src/main/java/org/dockbox/hartshorn/config/ConfigurationServiceProcessor.java#L48
Refactors the `strategies` field to be non-static, to avoid leaking to other states.
=> #562 Avoid leaking resource lookup strategies across application states

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/AnnotatedElementModifier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ElementModifier.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java
Fixes #564
This is a bit of a niche feature, but a feature nonetheless. Imagine we have a type which is processed internally by Hartshorn, this type will be evaluated based on its `TypeContext`, not on its `Class`. This gives us two major advantages, 1. better caching of commonly accessed values, and 2. better control of values.  
This suggestions makes explicit use of advantage 2. As we have full and autonomous control over these values, we can also add 'fake' or virtual values which don't exist on the `Class`. Values like annotations.  
> What I'd like is a way to add annotations to a `TypeContext`, or preferably even to `AnnotatedElementContext`s. This would allow us to 'modify' the present annotations, which can be useful for example in the `HartshornApplicationFactory` (see …
=> #564 Implement element modifiers, supporting virtual annotations

hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateJpaRepository.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateRemote.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateRemoteImpl.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/remote/PersistenceConnection.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SqlServiceTest.java
Fixes #570
Currently the driver and dialect for a `HibernateJpaRepository` always need to be defined beforehand through a `Remote` implementation.  
Adds a default remote implementation for `Hibernate` repositories. This remote acquires all required information from the application properties, and will validate them before attempting to construct a final connection.  
This allows you to create repositories without explicitely defining the connection.
* Platform: MySQL (container based)
=> #570 Configuration based remotes for `JpaRepository` instances

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/Hartshorn.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplication.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/logback/LogbackErrorConverter.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/FieldContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/exceptions/ApplicationException.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/exceptions/Except.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/exceptions/ExceptionHelper.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/exceptions/ExceptionLevel.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContextInjectionProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServiceModifier.java, hartshorn-core/src/main/resources/logback.xml, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ExceptionalTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateJpaRepository.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/AbstractPersistenceServiceModifier.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java
Fixes #574
> Due to generic type erasure, javac will allow you to rethrow a checked exception without requiring it to be checked. This can be done using the following method:  
> ```java
> public <T extends Throwable> void runtime(Throwable t) throws T {
>     throw (T) t;
> }
> ```
> 
> Currently, all unchecked rethrows of `ApplicationException` require it to be wrapped in a `RuntimeException` before it is (re)thrown. With the snippet above, you can rethrow the same exception without wrapping it, and without requiring it to be caught.  
> 
> Preferably this should be added to `Except`, and `ApplicationException#runtime` should be deprecated for removal.
Adds the snippet mentioned above to `Except` as a static utility, and replaces existing `throw ApplicationException.runtime()` usages …
=> #574 Add type-erasure based 'unchecked' exception rethrowing

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/test/java/com/example/application/ActivatorScanningTests.java, hartshorn-core/src/test/java/com/example/application/Demo.java, hartshorn-core/src/test/java/com/example/application/DemoImpl.java, hartshorn-core/src/test/java/com/example/application/UseDemo.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java
Fixes #585
These changes are made based on my earlier issue #585, where I stated that scannable prefixes in service activators were not applied even though they were registered.
> When registering additional prefixes through `ServiceActivator#scanPackages`, the prefixes are registered to the application environment, but are never processed to the application after that. This results in the prefix being known, but components and processors never being bound and/or activated. 
> https://github.com/GuusLieben/Hartshorn/blob/17c5b8afca8448583da02c00f0a3e5d641d97dbb/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L151
The solution for this issue was quite annoying to implement with the existing situation of registering and processing prefixes. …
=> #585 Separate prefix binding queue and processing of bound prefixes

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Fixes #586
Processors stored in `HartshornApplicationContext` are stored using a `MultiMap`, specifically the `ArrayListMultiMap`. However, as the `ApplicationContext` is one of the most concurrently accessed values, these processors should be stored in concurrent multimaps. I replaced usages with a `CustomMultiMap` using concurrent `Set`s as base collection.
https://github.com/GuusLieben/Hartshorn/blob/17c5b8afca8448583da02c00f0a3e5d641d97dbb/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L92-L93
=> #586 Replace processor storage with concurrent `CustomMultiMap` in `HartshornApplicationContext`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Fixes #588
> The `prefixes` argument in the constructor of `HartshornApplicationContext` is unused, as active prefixes are already handled by the `HartshornFactory`. 
> 
> https://github.com/GuusLieben/Hartshorn/blob/17c5b8afca8448583da02c00f0a3e5d641d97dbb/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L107
=> #588 Remove duplicated `prefixes` argument

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ElementContextTests.java
Fixes #591
Currently it is not allowed to reflect on TypeContext values. This was originally done to prevent accidental reflection on wrapped types. However, @pumbas600 pointed out that types may hold a field value with the type `TypeContext`. This will immediately fail as the check for `TypeContext` reflecting is present in the constructor of `TypeContext`.
Removes the rule within the `TypeContext` constructor. To allow users to easily check if a type is a `TypeContext`, I also added a `isTypeContext` rule. This is practically a shorthand for `.isChild(TypeContext.class)`.
=> #592 Allow reflecting on `TypeContext`s and add `isTypeContext` rule

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/JavaInterfaceProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/PassThroughFactory.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/Person.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/PersonImpl.java
Fixes #594
> When there is a default method in a proxied service interface, the default method cannot be invoked properly as the proceeding method method cannot be invoked directly using the `Proxy` instance.  
> 
> For example, say we have a `Person` interface which defines a name and age, and a `PersonImpl` with a constructor for these attributes. We wish to use a factory provider for this, so we do not need to be aware of the `PersonImpl` class. We also want to add a default value for `age` in our factory, so we don't need to implement that elsewhere. This results in the following factory service:
> ```java
> @Service
> public interface PassThroughFactory {
>     @Factory
>     Person create(String name, int age);
> 
>     default Person create(final String name) {
>         return …
```
=> #594 Resolve invocation of default methods in service proxies

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ElementContextTests.java
Fixes #597
Currently there is no integrated way of calling static methods directly through a `MethodContext`, the only alternative is invoking with a `null` instance.
Adds `invokeStatic` to the `MethodContext` type, with appropriate overloads. The invoker validates that the method is indeed static, before proceeding to invoke it without an existing instance of the declaring class.
=> #597 Add validated static invokers to `MethodContext`s

hartshorn-core/src/test/java/org/dockbox/hartshorn/core/boot/ComponentProvisionTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/testsuite/HartshornFactoryTests.java, hartshorn-core/src/testFixtures/java/org/dockbox/hartshorn/testsuite/HartshornExtension.java, hartshorn-core/src/testFixtures/java/org/dockbox/hartshorn/testsuite/HartshornFactory.java, hartshorn-i18n/src/test/java/org/dockbox/hartshorn/i18n/TranslationBatchGenerator.java
Fixes #596
Allows for the modification of the active `ApplicationFactory` which is used to create the `ApplicationContext` for a test class. This method should always be static, and should always return a valid `ApplicationFactory`.  
Optionally, the method may accept the existing `ApplicationFactory`, which has the default values loaded.  
The method is always annotated with `@HartshornFactory`, and should always be static.
```java
@HartshornFactory
public static ApplicationFactory<?, ?> factory(final ApplicationFactory<?, ?> factory) {
return factory.componentLocator(CustomComponentLocator::new);
}
```
=> #596 Allow modification of `ApplicationFactory` during test initialization

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodInvoker.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodModifier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ReflectionMethodInvoker.java
Fixes #601
Currently, the way methods are invoked through `MethodContext#invoke` and `#invokeStatic`, are limited to the default behavior of the `MethodContext`. The only way this can currently be changed, is by creating an override of the `MethodContext`. However this leaves internal invokers unchanged. https://github.com/GuusLieben/Hartshorn/blob/362a6a572e2df6a8ac97d4063579a21981d156ca/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodContext.java#L62
This PR introduces two relevant changes; method invokers, and method modifiers. A `MethodInvoker` is used by a `MethodContext` to determine how a method should be invoked. By default this uses the `ReflectionMethodInvoker` which uses Java Reflections to invoke methods, as has previously also been the default. …
=> #601 Allow modifying method invoker and access level

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocatorImpl.java, hartshorn-core/src/test/java/com/nonregistered/DemoComponent.java, hartshorn-core/src/test/java/com/nonregistered/NonRegisteredComponentTests.java, hartshorn-core/src/test/java/com/nonregistered/ThrowingComponentLocatorImpl.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java
Fixes #599
Currently it is not always clear when a component or service is not properly registered. This may lead to the component being used without it properly being processed early on.
When obtaining an instance of a type, the type will now be validated through the active `ComponentLocator`. If the type is a component, but is not registered, a warning will yield (default behavior). As previously indicated, this should not throw an exception by default, as components may be registered manually through other means.
=> #599 Validate that components are registered when requested

hartshorn-config/src/main/java/org/dockbox/hartshorn/config/ConfigurationComponentPostProcessor.java, hartshorn-config/src/main/java/org/dockbox/hartshorn/config/annotations/Value.java, hartshorn-config/src/test/java/org/dockbox/hartshorn/config/ConfigurationManagerTests.java, hartshorn-config/src/test/java/org/dockbox/hartshorn/config/DemoClasspathConfiguration.java, hartshorn-config/src/test/resources/junit.yml, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ApplicationPropertyHolder.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletHandler.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyErrorHandler.java
Fixes #605
Originally, #605 reported only that inline values were ignored due to `Value#or` taking priority even when its value is empty. 
> If a field annotated with `@Value` is defined as seen below, without the `sample.key` property being set, the value will always fall back to an empty or default value (in this case an empty `String`).
> ```java
> @Value("sample.key")
> private String key = "myDefaultValue";
> ```
> Expected behavior would be to fall back to `"myDefaultValue"`, as it is set inline, and should only be changed if the property is set or an alternative value is defined in the `@Value` annotation.  
@pumbas600 suggested deprecating `Value#or`, which has been done in this PR. Existing internal usages were updated accordingly.
During development for this, I noticed …
=> #605 Add support for inline default values and collection specifications to `@Value` based configuration postprocessor

hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JacksonDataMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JacksonObjectMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JavaPropsDataMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JsonDataMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/TomlDataMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/XmlDataMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/YamlDataMapper.java
Fixes #607
The internal `Mappers` enum inside `JacksonObjectMapper` uses direct imports to look up different `ObjectMapper` (Jackson) implementations. While this is fine when all dataformats are present on the classpath, this will yield a `NoClassDefFoundError`, causing the entire `JacksonObjectMapper` to be unusable.
Replaces the internal enum `Mappers` in `JacksonObjectMapper` with dedicated `JacksonDataMapper` implementations. These implementations are accessed through internal DI, allowing them to be overridden, as well as capturing classpath errors if the Jackson dataformat for the mapper is absent.
=> #607 Resolve direct use of Jackson data formats

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationConfigurator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocatorImpl.java, hartshorn-core/src/test/java/com/specific/sub/Demo.java, hartshorn-core/src/test/java/com/specific/sub/DemoService.java, hartshorn-core/src/test/java/com/specific/sub/DemoServicePreProcessor.java, hartshorn-core/src/test/java/com/specific/sub/SpecificPackageTests.java
Fixes #609
When a package prefix specifying a specific package like `com.example.specific` is bound to the active `ApplicationContext`, followed by a less specific package prefix being registered, like `com.example`, all components in `com.example.specific` will be processed twice.
All prefix bindings will now be queued so they can be filtered for broader packages before being processed. As this could impact annotation hierarchies, the prefix will be registered to the prefix context immediately when it is queued. 
=> #609 Resolve duplicate binding of overly specific packages when broader package is bound

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/bridge/Bob.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/bridge/BridgeImpl.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/bridge/BridgeParent.java
Fixes #611
`TypeContext#methods(Class<? extends Annotation>)` also includes synthetic bridge elements. While this makes sense to keep in `#methods()`, annotated elements should never include duplicates and bridge methods.  
This was first noticed by @pumbas600. When a `@Factory` processor attempts to process methods from inherited services, the bridge method is also present. This was caused by the simply hierarchy defined below:
```java
public interface DecoratorFactory<R, T, A extends Annotation> {
R decorate(T element, A annotation);
}
```
```java
@Service
public interface CooldownDecoratorFactory extends DecoratorFactory<CooldownDecorator, CommandContext, Cooldown> {
@Factory
@Override
CooldownDecorator decorate(CommandContext element, Cooldown annotation);
}
```
Here `#decorate` is …
=> #611 Filter synthetic bridge methods when looking up methods in `TypeContext`s

hartshorn-config/src/main/java/org/dockbox/hartshorn/config/ConfigurationComponentPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Component.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Service.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/JavassistApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistInterfaceHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/MethodInvoker.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainer.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainerImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentProxyPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FunctionalComponentPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceMethodPostProcessor.java, hartshorn-core/src/test/java/com/example/application/ActivatorScanningTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/boot/ComponentProvisionTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/NonProxyComponentType.java
Fixes #617
Currently proxies are only properly created through `ServiceMethodPostProcessor`s. This limits the presence of proxies to the presence of appropriate activators.
- Moves initialization of proxy components to `ComponentProxyPostProcessor`, where the component will first be validated
- Adds `permitProxying` to `Component` and `Service` stereotypes (both default to `true`)
- Adds `permitsProxying` to `ComponentContainer`
- Exposes delegated instance in `ProxyHandler`s
- Will no longer copy `static` fields in `ProxyHandler` proxy initializers
- Will now ensure methods are accessible when invoked dynamically in `ProxyHandler`s (due to `protected` methods)
=> #617 Add component-level proxy permission and global validated proxy processor

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/Context.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/Enable.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/Populate.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/Required.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ComponentProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/Context.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/DefaultContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/DelegatingContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ParameterLoaderContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/AnnotatedElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ExecutableElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistInterfaceHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/parameter/ContextParameterLoaderRule.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/parameter/ExecutableElementContextParameterLoader.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/parameter/GlobalProxyParameterLoader.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/parameter/RuleBasedParameterLoader.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/SetterInjectedComponent.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/SetterInjectedComponentWithAbsentBinding.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/SetterInjectedComponentWithNonRequiredAbsentBinding.java, hartshorn-core/src/testFixtures/java/org/dockbox/hartshorn/testsuite/HartshornTest.java
Fixes #619
Currently only two primary ways of injection are supported: field- and constructor injection. This means one other primary approach is currently missing: setter injection.
- Adds proper support for `@Enable`, `@Required`, `@Context`, and `@Inject` to executable context invokers
- Adds parameter loaders for the above parameter rules
- Adds setter/method injection during population phases
- Adds `@Populate` to allow/disallow field and executable injection during population phases
- Adds appropriate interface methods to `Context`, `ComponentProvider`, and `ApplicationContext` to support the changes mentioned above.
=> #619 Add support for setter/method injection

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/AnnotatedImpl.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/AnnotatedParent.java
When a type inherits from an annotated type, and wishes to modify the annotation contents of its parent, the type itself will be annotated with the same annotation, but with different values. To put that into code, consider the following example.
```java
public @interface SampleAnnotation {
boolean value();
}
```
```java
@SampleAnnotation(true)
public interface SampleParent { }
```
```java
@SampleAnnotation(false)
public class SampleImpl implements SampleParent { }
```
In this example, you'd expect `TypeContext.of(SampleImpl.class).annotation(SampleAnnotation.class)` to return `SampleAnnotation(value=false)` as the annotation is redefined on the implementation. However, as the lookup is performed iteratively on each parent, the annotation on `SampleParent` takes precendence at it was …
=> #621 Do not overwrite redefined annotations in `TypeContext` annotation validation

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServicePreProcessor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/factory/FactoryProvided.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/factory/FactoryService.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/factory/FactoryTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/factory/HighPriorityFactoryBound.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/factory/LowPriorityFactoryBound.java
During application startup, the `FactoryServicePreProcessor` looks up the appropriate constructor of the implementation of the return type of the method. However, when there is more than one binding present, this lookup would reverse their priority causing the lowest priority to be bound, instead of the highest priority.
Fixes #627
=> #627 Resolve factory bindings not respecting correct binding priorities

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ParameterLoaderContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ConstructorContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ExecutableElementContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/MethodContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ParameterContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContextInjectionPreProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/parameter/GlobalProxyParameterLoader.java, hartshorn-web/src/test/java/org/dockbox/hartshorn/web/RequestArgumentProcessorTests.java
Currently, there's no way to directly get the declaring class of an `ExecutableElementContext<?>` without having to do:
```java
if (executable instanceof MethodContext methodContext)
return methodContext.parent();
return ((TypedElementContext<?>) executable).type()
```
As `Executable` defines `#getDeclaringClass`, it is safe to expose the parent directly through the `ExecutableElementContext`.
Fixes #628
=> #628 Expose declaring parent through executable element context

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/AnnotatedElementContext.java
Currently the only way to get all annotations annotated with a given annotation of a given element is to use `AnnotatedElementContext#annotations().stream().filter(a -> a.annotation(MyAnnotation.class).present()).toList()`. While this works fine, it's a common source of code duplication and thus potential errors.
To resolve this a new utility method was added to `AnnotatedElementContext` allowing you to get all annotated annotations on an element.
Fixes #625
=> #625 Allow obtaining annotated annotations on a given element

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/activate/AutomaticActivation.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-i18n/src/test/java/org/dockbox/hartshorn/i18n/TranslationBatchGenerator.java
While running unit tests and debugging service post-processors for unrelated reasons, I noticed that translation injectors (service methods annotated with `@InjectTranslation`) are processed twice by the `TranslationInjectPostProcessor`. I noticed the first processor was indeed a proper instance of `TranslationInjectPostProcessor`, however the second time it was processed the processor instance was a `KeyGen`.  
The `KeyGen` in the translation batch generator does indeed extend `TranslationInjectPostProcessor`. However as demonstrated, this does lead to duplicate processing. While this may not be a breaking issue in this scenario, it may lead to issues in other scenarios.
As the `KeyGen` is not used as a dedicated processor, but rather as a way to expose protected methods in …
=> #622 Disable automatic `KeyGen` activation

.github/workflows/hartshorn.yml, build.gradle, examples/examples.gradle, gradle.properties, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationConfigurator.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SqlServiceTest.java
Updates relevant dependencies to the latest compatible version.
- FreeFair Javadoc Aggregate plugin, this has not worked correctly for some time now
- Removes Log4J dependencies from `examples` module, these were no longer used
- Updates CadixDev Licenser from 0.5.0 to 0.6.1
- Updates OWASP Dependency Check from 6.2.2 to 6.5.1
- Updates CheckerFramework from 0.6.3 to 0.6.5
- Updates Gradle Lombok from 1.6 to 5.0.0
- Downgrades Logback from 1.3.0-alpha10 to 1.2.10 (due to accidental alpha usage)
- Updates Microsoft SQL Server driver from 9.4.0.jre11 to 9.4.1.jre11
- Updates JavaX Servlet API from 3.1.0 to 4.0.1
- Updates PostgreSQL driver from 42.2.23 to 42.3.1
- Updates MySQL driver from 8.0.26 to 8.0.27
- Updates TestContainers from 1.16.0 to 1.16.2
- Updates Derby driver from 10.8.2.2 …
=> RC Dependency check

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/Unproxy.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/JavassistApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/ProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistInterfaceHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/ObjectEqualsParameterLoaderRule.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/UnproxyParameterLoaderRule.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/UnproxyingParameterLoader.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentProxyPostProcessor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java
When `#equals` was called on a proxy object, the method call would be handled as follows:
`proxyA.equals(proxyA)` -> `proxyHandler.invoke(method = #equals, args = [proxyA])` -> `delegate.equals(proxyA)`
As there is no explicit implementation of `#equals` in `proxyA`, this would redirect to the native implementation defined in `Object`, which performs a sameness check `this/delegate == proxyA`, which is `false`.  
To resolve this, the incoming argument should be unproxied, so the argument becomes `delegate` when it is received by `delegate#equals`. However, this leaves one final issue: interface proxies have no delegate instances, so there is no explicit `#equals` method to fall back to. This too has been resolved by performing the equality check inside the proxy handler, checking the …
=> #635 Resolve `#equals` failing on native proxy objects

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java
`TypeContext#contextsFromParameterizedType` does not look up `ParameterizedType`s, causing e.g. the signature `List<Set<String>>` to have a `TypeContext<List>` without type parameters, as the `Set<String>` is a parameterized type instead of a direct class reference or wildcard. See #636 for further explanation and testing scenario.
Fixes #636
=> #636 Recursively look for parameterized types in `TypeContext#contextsFromParameterizedType`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/AbstractActivatingApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/AbstractApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ClasspathResourceLocator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornApplicationManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/HartshornClasspathResourceLocator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ObservableApplicationManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/SelfActivatingApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/AbstractPrefixContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationEnvironment.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ModifiableContextCarrier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/PrefixContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ReflectionsPrefixContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/testsuite/HartshornFactoryTests.java
Currently the active `PrefixContext` of a given `ApplicationEnvironment` can not be configured at all. The existing implementation, `ReflectionsPrefixContext` is hardcoded into the `HartshornApplicationEnvironment`.
https://github.com/GuusLieben/Hartshorn/blob/7c321cda4b2b4c07de8ed477bc184add17f57447/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationEnvironment.java#L40
This PR adds the option to configure a custom prefix context, using the `ReflectionsPrefixContext` as the default implementation.  
Additionally, the existing `HartshornApplicationFactory` has been split into dedicated abstract factories, to allow for easier custom implementations.
Fixes #644
=> #644 Restructure application factories and permit custom prefix context

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java
By default, only the `ApplicationLogger` type is bound, while the `org.slf4j.Logger` it provides is not. This PR adds a default supplier-based binding to the provided logger.
Fixes #651
=> #651 Add default `org.slf4j.Logger` binding to `ApplicationLogger` provided logger

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/FieldContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java
In specific cases, such as providing license keys or other similar values, it can be useful to define the following component provider:
```java
@Service
public class LicenseService {
@Provider("license")
public String license() {
return "MyLicenseKey";
}
}
```
However, this yields an exception when obtaining the component (applicationContext.get(Key.of(String.class, "license"))) as fields are attempted to be populated on a closed module.
```java
Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @44e81672
```
As this is caused by the `setAccessible(true)` statement (see below), this can be resolved by replacing said statement with `trySetAccessible()`. As this only affects get/set actions on hidden …
=> #649 Don't attempt to access types from closed module(s)

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Component.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainer.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainerImpl.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/NonProcessableType.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/NonProcessableTypeProcessor.java
Currently all components are automatically processed when it passes any `ComponentProcessor`'s preconditions. However, it may not always be desired that a component is processed. This may be to circumvent specific modifications, for testing purposes, or other specific use-cases.  
This PR adds a new attribute to the component stereotype: `permitProcessing`. Like `permitProxying`, this indicates specifically how the component should be treated during post-processing. While `permitProxying` targets specific processors, `permitProcessing` will target the proccessing job itself. If it is set to `false`, the component will not be processed by any processor.
Fixes #639
=> #639 Add `permitProcessing` to component stereotype

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Currently all objects will be processed when they are requested through the active application context. However, this may lead to unexpected behavior on third-party objects.  
To ensure no third-party objects are mistakingly processed, we now ensure only explicit components are processed. An explicit component is a component that is registered to the `ComponentLocator`, or has an active `ComponentContainer`.  
Any instance provided will still be populated if it has `@Context` and/or `@Inject` markers.
Fixes #640
=> #640 Don't process non-explicit components

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/MultiMap.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocatorImpl.java
#662 reports that components may be processed twice if they are on two partial prefix matches. In this case that meant that any prefix that matched both `nz.pumbas.*` and `nz.pumbas.halpbot.*` would be processed twice.  
The direct solution is relatively easy, which is to filter the incoming components in the `ComponentLocator` implementation. However @pumbas600's logs indicated a second issue; the locating order was completely incorrect.
```java
11:53:25.960 [ main           ] @ 18284 -> o.d.h.c.s.ComponentLocatorImpl         INFO  - Located 46 components with prefix nz.pumbas.halpbot in 145ms 
11:53:26.001 [ main           ] @ 18284 -> o.d.h.c.s.ComponentLocatorImpl         INFO  - Located 21 components with prefix org.dockbox.hartshorn in 12ms 
11:53:26.024 [ main           ] @ 18284 …
```
=> #662 Resolve components being processed twice on partial prefixes

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/InjectorMetaProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/MetaProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/Provider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ProviderServicePreProcessor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/NonProcessableTypeProcessor.java, hartshorn-core/src/test/java/test/types/provision/FieldProviderService.java, hartshorn-core/src/test/java/test/types/provision/SampleProviderService.java
Currently when a field value is injected, for example through `@Value`, the only way to turn this into a provider is by creating a getter for the field and annotating the getter with `@Provider`. For example:
```java
@Configuration(source = "classpath:license", filetype = FileFormats.PROPERTIES)
public class MyLicense {
@Value("license.key")
private String licenseKey;
@Singleton
@Provider("license")
public String get() {
return this.licenseKey;
}
}
```
This PR adds the ability to mark fields with `@Provider`, which allows you to directly create a binding of that field. For example:
```java
@Configuration(source = "classpath:license", filetype = FileFormats.PROPERTIES)
public class MyLicense {
@Singleton
@Provider("license")
@Value("license.key")
private String licenseKey;
}
```
Fixes #661
=> #661 Add field-support to `@Provider`

hartshorn-cache/hartshorn-cache.gradle, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/CacheImpl.java, hartshorn-commands/hartshorn-commands.gradle, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/cli/SimpleCommandCLI.java, hartshorn-events/hartshorn-events.gradle, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/AbstractTask.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/PipelineTask.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/SimpleTaskRunner.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/Task.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/TaskRunner.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/ThreadUtils.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/ThreadUtilsImpl.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/CancelBehaviour.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/PipelineDirection.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/exceptions/IllegalPipeException.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/exceptions/IllegalPipelineException.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipelines/AbstractPipeline.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipelines/ConvertiblePipeline.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipelines/ConvertiblePipelineSource.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipelines/Pipeline.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/CancellablePipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/ComplexPipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/EqualPipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/IPipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/InputPipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/ListenerPipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/OutputPipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/Pipe.java, hartshorn-tasks/src/main/java/org/dockbox/hartshorn/core/task/pipeline/pipes/StandardPipe.java
The Tasks API has gone largely unused, the only reference to `ThreadUtils` being an unused reference in the `SimpleCommandCLI` (to be removed), and the `TaskRunner` being used once in the `CacheImpl` (to be replaced).
https://github.com/GuusLieben/Hartshorn/blob/21a262a874a430ff190f9152a40a5f3fd22f2a95/hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/cli/SimpleCommandCLI.java#L46
https://github.com/GuusLieben/Hartshorn/blob/21a262a874a430ff190f9152a40a5f3fd22f2a95/hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/CacheImpl.java#L72
All types of the Tasks API have been marked for removal. The Pipeline API has been marked for removal from Hartshorn, and has been moved to a separate repository at https://github.com/GuusLieben/JPipelines
Fixes #667
=> #667 Deprecate Tasks API

examples/src/caching/java/org/dockbox/hartshorn/demo/caching/services/CachingService.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/context/MethodCommandExecutorContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/HartshornUtils.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/MultiMap.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/HartshornUtilTests.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JacksonObjectMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/mapping/ObjectMapper.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/handle/EventHandlerRegistry.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/MessageTemplate.java, hartshorn-i18n/src/test/java/org/dockbox/hartshorn/i18n/TranslationBatchGenerator.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java
`HartshornUtils#emptyMap` was originally supposed to be deprecated by #659, however it was originally missed when deprecating. This PR removes the utility method, and refactors existing usages.
Fixes #670
=> #670 Deprecate `HartshornUtils#emptyMap`

hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheEvictionMethodPostProcessor.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheServicePostProcessor.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheUpdateMethodPostProcessor.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CachedMethodPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ContextMethodPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServicePostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ProxyDelegationPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceAnnotatedMethodInterceptorPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceAnnotatedMethodPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceMethodInterceptorPostProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/AbstractPersistenceServicePostProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/QueryPostProcessor.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/services/TranslationInjectPostProcessor.java
The names `ServiceMethodPostProcessor` and `ServiceAnnotatedMethodPostProcessor` suggest the method is processed, which is correct, but does not disclose the fact that methods will be intercepted as proxy methods. 
https://github.com/GuusLieben/Hartshorn/blob/21a262a874a430ff190f9152a40a5f3fd22f2a95/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceAnnotatedMethodPostProcessor.java
https://github.com/GuusLieben/Hartshorn/blob/21a262a874a430ff190f9152a40a5f3fd22f2a95/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceMethodPostProcessor.java
This PR renames these processors to `ServiceMethodInterceptorPostProcessor` and `ServiceAnnotatedMethodInterceptorPostProcessor`, respectively. This way the processors clearly disclose their purpose.  
For …
=> #672 Rename ambiguous `ServiceMethodPostProcessor` and `ServiceAnnotatedMethodPostProcessor`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/testsuite/HartshornFactoryTests.java
Currently the CLI argument pattern is `-Hproperty=value`, which was originally chosen as the `-H` prefix would indicate the argument is used by Hartshorn. However this often leads to properties such as `-Hhartshorn.data.url` which becomes hard to read.  
This PR replaces the pattern with `--property=value`, so properties will be more readable. Considering these are passed as application arguments, it is to be expected that these will be used within Hartshorn either way.
Fixes #674
=> #674 Update CLI pattern for readability

hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/CacheFactory.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/annotations/CacheService.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/annotations/Command.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/arguments/DefaultArgumentConverters.java, hartshorn-commands/src/test/java/org/dockbox/hartshorn/commands/CommandDefinitionContextTests.java, hartshorn-config/src/main/java/org/dockbox/hartshorn/config/annotations/Configuration.java, hartshorn-config/src/test/java/org/dockbox/hartshorn/config/DemoFSConfiguration.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/inject/ComponentBinding.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Component.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Service.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/AbstractActivatingApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ApplicationProviders.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/AccessorFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainer.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainerImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceImpl.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/TransactionFactory.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/JpaRepositoryFactory.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletFactory.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/MvcController.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/PathSpec.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/annotations/RestController.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/servlet/WebServletFactory.java
Currently most internal services are not explicitely marked with service activators, causing them to always be active. This specifically targets `Service#activators`. This PR adds required service activators to all internal services to prevent them from being activated when they shouldn't be activated. Services which are already marked correctly have been ignored.  
In addition to this, I also made sure services are now correctly activated directly after the application context is created. This ensures services can start processes where needed. This can be toggled on/off by changing the `lazy` attribute on applicable services. All service stereotypes can be lazy-loaded, however they will always be pre-processed as long as the appropriate activators are present.
Fixes #666
=> #666 Lazy-loading components and add required service activators to internal services

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ReflectionMethodInvoker.java, hartshorn-test-suite/src/main/java/org/dockbox/hartshorn/testsuite/HartshornExtension.java
Methods are not made accessible by default in a new `MethodContext`. Because of this, protected and private methods cannot be invoked by default. This leads to `HartshornExtension` being unable to invoke protected and static factory modification methods (annotated with `@HartshornFactory`).
This PR ensures the invoked method is accessible before making any attempts to invoke it. This is handled by the `HartshornExtension`, and _not_ the invoker itself to follow proper invocation conventions.
Fixes #680
=> #680 Ensure `ApplicationFactory` modifiers are accessible during unit tests

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/proxy/javassist/JavassistProxyHandler.java
Currently the processing part of components created by the `HartshornApplicationContext` is implemented as follows:
https://github.com/GuusLieben/Hartshorn/blob/97ae8f7bdbd7b957a6be98066d98163e2aa50e9f/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L356-L381
Especially both phases are almost 100% identical, with the one difference being that phase 1 permits mutable instances, while phase 2 does not.
Phase 1:
https://github.com/GuusLieben/Hartshorn/blob/97ae8f7bdbd7b957a6be98066d98163e2aa50e9f/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java#L356-L363
Phase 2:
https://github.com/GuusLieben/Hartshorn/blob/97ae8f7bdbd7b957a6be98066d98163e2aa50e9f/hartshorn-core/src/main/java/org/dockbox/hartshorn …
=> #681 Clean up ordered processing in `HartshornApplicationContext`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/AbstractActivatingApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/ApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/HartshornApplicationContext.java
Currently the type responsible for closing an active `ApplicationContext` is the `ApplicationFactory`. In implementation details, this would be the `AbstractActivatingApplicationFactory` specifically. This leads to two issues:
1. The responsibility shifts to a non-managed component
2. The application context is only closed when the runtime shuts down
Both these issues are especially relevant in applications where the application lifecycle may end long before the runtime exits. An example of this is contexts activated through JUnit.
To allow environments to close an application context manually, before the runtime exits, this PR implements `Closeable` in the `ApplicationContext` interface. The concrete implementation mimicks the current implementation in the …
=> #678 Implement `Closeable` in `ApplicationContext`

examples/src/commands/java/org/dockbox/hartshorn/demo/commands/services/CommandCLIStarterService.java, examples/src/persistence/java/org/dockbox/hartshorn/demo/persistence/services/EventListenerService.java, examples/src/persistence/java/org/dockbox/hartshorn/demo/persistence/services/UserCommandService.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/CommandListener.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/CommandListenerImpl.java, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/CommandProviders.java
The `SimpleCommandCLI` currently uses an explicitly created `Thread` to run in asynchronous mode. This means the thread the action is performed on is unmanaged.
https://github.com/GuusLieben/Hartshorn/blob/97ae8f7bdbd7b957a6be98066d98163e2aa50e9f/hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/cli/SimpleCommandCLI.java#L76
This PR migrates this explicit call to a `ExecutorService` through a simple `Executors.newSingleThreadExecutor()`. This ensures the thread is correctly destroyed after the CLI exits.  
Additionally, as I suggested in #679, I moved the implementation out of the `cli` package so it is at the same level as its interface. These have also both been renamed to be `CommandListener` instead of `CommandCLI`.
Fixes #679
=> #679 Replace explicit `Thread` creation with managed service executor and refactor `CommandListener`

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ReflectTests.java
When a wildcard type parameter is encountered, a new `WildcardTypeContext` is returned. While this is valid for wildcards without upper bounds (e.g. `List<?>`) this is not valid for wildcards _with_ upper bounds (e.g. `List<? extends String?`).
This PR adds support for wildcards with upper bounds. This returns a TypeContext of the upper bounds (e.g. `? extends String` becomes `TypeContext<String>`).
Fixes #691
=> #691 Add support for wildcards with explicit upper bounds

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/Factory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/FactoryContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServicePostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/FactoryServicePreProcessor.java
Currently, all `@Factory` methods are validated on startup. This ensures every factory method has an appropriate bound constructor on the target type. However sometimes it may be preferred to make this binding optional.
This PR adds an option to make factory bindings optional. If a factory binding is optional, and no bound constructor is found, it will then ignore this instead of throwing an exception.  
When post-processing, this is also correctly handled. If no bound constructor is available, the processor will fall back to returning `null`. If the factory is required the post processor will always yield an exception.
By default all factory methods are required unless specifically marked as non-required.
Fixes #693
=> #693 Add support for non-required factory validation

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Component.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/annotations/stereotype/Service.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ActivatorPresenceActivationFilter.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentActivationFilter.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainer.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainerImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocatorImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ServiceImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/TypePresenceActivationFilter.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateProviders.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JacksonProviders.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/jetty/JettyProviders.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/mvc/freemarker/FreeMarkerProviders.java
Currently, components are always activated when the required service activator is present. However, this does not keep in mind that different implementations may exist for the same component bindings. For example, the `ObjectMapper` type defaults to the use of Jackson for object (de)serialization. However, it is likely that another implementation would use Gson instead. With the activator being unaware of the implementation, both would be bound.
This PR introduces a way for components to activate only when specific types are available. This is done through the new `Component#requires` attribute, which allows types to define the fully qualified names of required types. When one or more of these types are absent, the component will not activate by default.  
Filters are applied through the …
=> #699 Component activation filtering and type presence checks

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/StandardDelegatingApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentContainerImpl.java
Adds a previously missing implementation for `#singleton(Key, S)` in `StandardDelegatingApplicationContext`. This delegates the method to the `StandardComponentProvider` in the context.  
Additionally, the rule to permit proxying on components will now also filter whether processing is permitted in the first place.
Fixes #707
=> #707 Add missing implementation for `StandardDelegatingApplicationContext` `#singleton(Key, S)`

examples/src/persistence/java/org/dockbox/hartshorn/demo/persistence/services/UserRepository.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ClassLoaderClasspathResourceLocator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/ClasspathResourceLocator.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/core/boot/Resources.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ClassPathResourceLookupStrategy.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationProviders.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationServicePreProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/FileSystemLookupStrategy.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ResourceLookupStrategy.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/annotations/Configuration.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/DemoClasspathConfiguration.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/DemoFSConfiguration.java, hartshorn-data/src/test/resources/junit.properties, hartshorn-data/src/test/resources/junit.yml
When using a non-default (YAML) file for `@Configuration` types, it is always required to provide the file type. However this leads to strict binding to a given file type.  
With this PR, configurations will automatically scan for all files with the given filename in the configured location. If one or more files exists, each file will be used. If multiple files exist a warning will be given, to indicate potential property duplication. If no files exist the behavior depends on the value of `Configuration#failOnMissing`. If this is `true`, an error will yield. If it is `false` a warning log will be added but the application will proceed, this is the default behavior.
Fixes #650 
Additionally, fallback sources were added. This changes the source definition in `@Configuration` to an array …
=> #650 Automatic configuration filetype detection and #656 configuration fallback sources

hartshorn-core/src/test/java/org/dockbox/hartshorn/core/boot/ComponentProvisionTests.java, hartshorn-i18n/src/test/java/org/dockbox/hartshorn/i18n/TranslationBatchGenerator.java, hartshorn-test-suite/src/main/java/org/dockbox/hartshorn/testsuite/HartshornExtension.java, hartshorn-test-suite/src/main/java/org/dockbox/hartshorn/testsuite/HartshornLifecycleExtension.java, hartshorn-test-suite/src/main/java/org/dockbox/hartshorn/testsuite/HartshornTest.java
> The `HartshornExtension` in the test suite is designed to support a per-method lifecycle, however this may not always be the case. When a test class is annotated with `@TestInstance(Lifecycle.PER_CLASS)` the lifecycle is no longer maintained per method, making it so `beforeEach` and `afterEach` are no longer called in `HartshornExtension`.
These changes will dynamically support per class and per method lifecycles. This is useful for (for example) parameterized tests which depend on the application context, like the `ComponentProvisionTests` which tests for all default components.
Fixes #724
=> #724 Support per class lifecycle in test suite

hartshorn-core/src/main/java/org/dockbox/hartshorn/inject/binding/ComponentInstanceFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/javassist/JavassistProxyFactory.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java
Fixes the following test:
https://github.com/GuusLieben/Hartshorn/blob/d29dc1648efec1db60bef1d15dafbae0630386bf/hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java#L375-L383
This was caused by the ClassLoader for `org.dockbox.hartshorn.proxy.Proxy` being different from the one responsible for the Lambda. By looking up the default ClassLoader for both, this works correctly. Appropriate fallbacks have been put in place to handle the situation where the default ClassLoader is either unavailable or not accessible.
Fixes #726
=> #726 Fix lambda proxying in different classloader

hartshorn-core/src/main/java/org/dockbox/hartshorn/util/reflect/TypeContext.java
Removes unimplemented PropertyDescriptor methods from TypeContext. #718 mentions these were scheduled for implementation, but were since marked for removal.
Finalizes #718
=> #718 Remove property descriptors from TypeContext

hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/ApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/StandardDelegatingApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/HierarchicalApplicationComponentProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ComponentFinalizingPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ComponentPreProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ComponentProcessingContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ComponentProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/FunctionalComponentPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ProcessingOrder.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ProcessingPhase.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/HartshornApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/Proxy.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/PhasedProxyCallbackPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ProxyDelegationPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ServiceAnnotatedMethodInterceptorPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ServiceAnnotatedMethodPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ServiceMethodInterceptorPostProcessor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/NonProcessableTypeProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationComponentPostProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/TransactionalProxyCallbackPostProcessor.java
Originally, #717 was opened to avoid populating non-components. Since then, this was resolved by #720. However, the concept of moving component population out of the component provider entirely stuck with me.  
The logical way of doing this is to follow the original suggestion I made in #717; move population to a post processor. This is possible in phase 2 of component provision, as it only modifies the state of a component, without potentially discarding the instance (e.g. for proxy instances).  
A next step was to clean up the entire component finalization process. This is made up of two primary steps:
1. Finalize proxy instance
2. Populate outgoing instance
So after step 2 is covered, we are left with step 1 as it is required to be performed before step 2 can be performed. Step 1 is …
=> #717 Migrate instance population to post processor

hartshorn-core/src/main/java/org/dockbox/hartshorn/component/HierarchicalApplicationComponentProvider.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/annotations/ConfigurationObject.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/annotations/UseConfigurations.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/config/PropertyHolder.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/config/StandardPropertyHolder.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JacksonObjectMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/mapping/ObjectMapper.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/ConfigurationObjectPostProcessor.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/ConfigurationManagerTests.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SampleConfigurationObject.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SampleSetterConfigurationObject.java
Currently `@Value` is the only way to easily inject configuration values. While this previously made sense as this would only support basic types (`String`s, `Collection`s, and primitives), #731 introduced support for complex configuration types.
This PR adds a new explicit configuration stereotype for `@Component`, to allow the instance to be created based on configuration values through the `PropertyHolder`. If the instance already exists when the component processor is entered, the existing instance will be updated, instead of being replaced with a new instance (even if the processing phase technically permits it).
Fixes #733
=> #733 Add support for configuration objects

build.gradle, gradle.properties, gradle/publications.gradle, hartshorn-cache/hartshorn-cache-caffeine/hartshorn-cache-caffeine.gradle, hartshorn-cache/hartshorn-cache.gradle, hartshorn-commands/hartshorn-commands.gradle, hartshorn-core/hartshorn-core.gradle, hartshorn-core/hartshorn-proxy-cglib/hartshorn-proxy-cglib.gradle, hartshorn-core/hartshorn-proxy-javassist/hartshorn-proxy-javassist.gradle, hartshorn-data/hartshorn-data.gradle, hartshorn-events/hartshorn-events.gradle, hartshorn-i18n/hartshorn-i18n.gradle, hartshorn-i18n/src/test/java/org/dockbox/hartshorn/i18n/TranslationBatchGenerator.java, hartshorn-web/hartshorn-web.gradle, settings.gradle
Updates license headers for Gradle configurations, which were previously missed and thus outdated.
Closes #668
=> #668 Update license headers for Gradle configurations

hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/expression/RangeExpression.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/interpreter/Interpreter.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/lexer/Lexer.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/parser/Parser.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/semantic/Resolver.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/token/TokenType.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/visitors/ExpressionVisitor.java, hartshorn-hsl/src/test/resources/array/array_range.hsl
Currently if you wish to quickly populate a list with increasing values (e.g. `[1,2,3,..8,9,10]`), the best approach is to create an empty array, and loop until it is populated:
```js
var array = [null] * 10;
for (var i=0; i<10; i++) {
array[i] = i+1;
}
```
While this is fine, HSL is intended to be compact so it can be used easily in short expressions.
These changes add a shorthand for the sample above, a typical example of this would be:
```js
for (var i in 1..10) {
print(i);
}
```
Both the min and max are inclusive. For example, the sample above yields `[1,2,3,4,5,6,7,8,9,10]`
Fixes #789
=> #789 Range shorthand expression

hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/statement/ConstructorStatement.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/statement/FunctionStatement.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/statement/NativeFunctionStatement.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/statement/ParametricExecutableStatement.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/interpreter/Interpreter.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/modules/AbstractNativeModule.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/objects/virtual/VirtualFunction.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/parser/Parser.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/semantic/Resolver.java
Currently parameters are directly exposed as `Token`s. While this is fine in the current implementation, it limits future expansion.
These changes add a dedicated `Parameter` object. This currently only wraps around the `Token`, but will be used in the future to support strong typing as well.
Fixes #790
=> #790 Add context object for function parameters

gradle.properties, hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/CommandGatewayImpl.java, hartshorn-core/hartshorn-core.gradle, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/AbstractApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/ApplicationContextConfiguration.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/ApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/InitializingContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/StandardApplicationFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/DelegatingApplicationContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/ComponentPostConstructor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/ComponentPostConstructorImpl.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/ComponentProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/HierarchicalApplicationComponentProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/factory/FactoryServicePostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/inject/Enable.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/SingletonEnableable.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateDataSourceList.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateEntityManagerCarrier.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateJpaRepository.java, hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SqlServiceTest.java, hartshorn-web/src/main/java/org/dockbox/hartshorn/web/ServletHandler.java
Originally, `Enableable` was added as a simple way to allow actions to be performed after injection was performed, but before the component was put in use. However, this could be simplified (and streamlined) by supporting the `@PostConstruct` annotation instead.
This PR implements these changes to replace `Enableable` with `@PostConstruct` support. Instead of deprecating `Enableable`, it was removed as it was only used in very few places, and known third-party usages are currently not commonly using this.
Fixes #799
=> #799 Add `@PostConstruct` support for managed components

build.gradle.kts, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/condition/ProvidedParameterContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/inject/binding/ConcurrentHashSingletonCache.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/reflect/Parameter.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/reflect/ParameterContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/reflect/TypeContext.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventBus.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventBusImpl.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventExecutionFilterBeanListener.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventExecutionFilterContext.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/EventProviders.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/handle/ConditionMatcherEventExecutionFilter.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/handle/EventExecutionFilter.java, hartshorn-events/src/main/java/org/dockbox/hartshorn/events/handle/EventHandler.java, hartshorn-events/src/test/java/org/dockbox/hartshorn/events/EventBusTests.java, hartshorn-events/src/test/java/org/dockbox/hartshorn/events/SampleNamedEvent.java, hartshorn-events/src/test/java/org/dockbox/hartshorn/events/TestEventBus.java, hartshorn-events/src/test/java/org/dockbox/hartshorn/events/listeners/ConditionalEventListener.java, hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/condition/ExpressionCondition.java
Recently we added support for condition matching on annotated elements. This is currently used to allow filtering of active components and providers. However, this is not yet supported in event listeners.
This PR adds support for condition matching in event listeners. Additionally, it adds the `ProvidedParameterContext`, to allow provided parameters to be provided to other validators like condition matchers.
Fixes #804
=> #804 Condition matching for event listeners

.gitignore, build.gradle.kts, gradle/libs.versions.toml, hartshorn-core/src/test/groovy/org/dockbox/hartshorn/core/groovy/GroovyClassComponent.groovy, hartshorn-core/src/test/groovy/org/dockbox/hartshorn/core/groovy/GroovyComponentTests.groovy, hartshorn-core/src/test/groovy/org/dockbox/hartshorn/core/groovy/GroovyInterfaceComponent.groovy, hartshorn-core/src/test/groovy/org/dockbox/hartshorn/core/groovy/GroovyTraitComponent.groovy, hartshorn-core/src/test/kotlin/org/dockbox/hartshorn/core/KotlinClassComponent.kt, hartshorn-core/src/test/kotlin/org/dockbox/hartshorn/core/KotlinComponentTests.kt, hartshorn-core/src/test/kotlin/org/dockbox/hartshorn/core/KotlinInterfaceComponent.kt, hartshorn-core/src/test/kotlin/org/dockbox/hartshorn/core/KotlinObjectComponent.kt, hartshorn-core/src/test/kotlin/org/dockbox/hartshorn/core/KotlinSealedInterfaceComponent.kt, hartshorn-core/src/test/scala/org/dockbox/hartshorn/core/scala/ScalaCaseClassComponent.scala, hartshorn-core/src/test/scala/org/dockbox/hartshorn/core/scala/ScalaClassComponent.scala, hartshorn-core/src/test/scala/org/dockbox/hartshorn/core/scala/ScalaComponentTests.scala, hartshorn-core/src/test/scala/org/dockbox/hartshorn/core/scala/ScalaObjectComponent.scala, hartshorn-core/src/test/scala/org/dockbox/hartshorn/core/scala/ScalaTraitComponent.scala, hartshorn-data/src/test/resources/junit.properties, hartshorn-data/src/test/resources/junit.yml, hartshorn-i18n/src/test/resources/i18n/en_us.yml
Currently we 'know' other JVM languages are supported by Hartshorn, but this knowledge is not backed by tests. This PR adds tests for the following languages, to verify their supported data types are compatible with Hartshorn:
- Kotlin 1.7.10
- Scala 2.13.8
- Groovy 4.0.2
Minor note: downgrades SLF4J from 2.0.0 to 1.7.36 due to compatibility issues with Logback.
Fixes #812
=> #812 Verify JVM language compatibility

hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ComponentFinalizingPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/JDKInterfaceProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/ProxyConstructorFunction.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/ProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CglibProxyConstructorFunction.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CglibProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/javassist/JavassistProxyConstructorFunction.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/javassist/JavassistProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/reflect/ExecutableElementContext.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ConcreteProxyWithNonDefaultConstructor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java
Currently all proxy factories assume there is either a default constructor, or no constructor at all present in the target type for the proxy. However, when a type is provided which does not meet this expectation, the proxy cannot be created (as there is not enough information to do so). A similar type may look like:
```java
public class ConcreteProxyWithNonDefaultConstructor {
public ConcreteProxyWithNonDefaultConstructor(final ApplicationContext applicationContext) {
// ...
}
}
```
These changes allow us to provide a target constructor and set of arguments to create a proxy instance of a similar type. This has also been implemented in the component finalizer, so component provision uses the optimal (injectable) constructor.
Fixes #815
=> #815 Allow creation of concrete proxies of types with non-default constructor(s)

hartshorn-core/src/main/java/org/dockbox/hartshorn/application/DefaultApplicationBuilder.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/MethodInvokable.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CGLibProxyMethodInvokable.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CglibApplicationProxier.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CglibProxyConstructorFunction.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CglibProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/cglib/CglibProxyLookup.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/introspect/reflect/view/ReflectionTypeView.java
CGlib is not officially supported in newer JDKs, and therefore risks instability issues when used in Hartshorn as we target Java 17+. This PR deprecates CGlib as the primary proxier, and uses Javassist as preferred option instead. CGlib support has not been marked for removal, though a warning will be given when it is used.
```
You are using CGLib, which is not actively maintained and may cause issues with Java 9+.
This may cause unexpected behavior or significant errors during the application runtime.
It is recommended to use the Javassist proxier instead.
```
Fixes #837
=> #837 Deprecate CGlib proxying

hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheEvictionMethodPostProcessor.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheServicePostProcessor.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CacheUpdateMethodPostProcessor.java, hartshorn-cache/src/main/java/org/dockbox/hartshorn/cache/modifiers/CachedMethodPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/component/factory/FactoryServicePostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/CustomInvocation.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/DefaultProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/LazyProxyManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/MethodInterceptor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/MethodInterceptorContext.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/ProxyFactory.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/ProxyManager.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/StandardMethodInterceptor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ContextMethodPostProcessor.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ServiceMethodInterceptorPostProcessor.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/proxy/ProxyTests.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/serialization/DeserializerMethodPostProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/serialization/SerializerMethodPostProcessor.java, hartshorn-data/src/main/java/org/dockbox/hartshorn/data/service/QueryPostProcessor.java, hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/services/TranslationInjectPostProcessor.java
Method interceptors currently do not have a unified way of checking whether a value matches the expected return type. This risks cast exceptions, or otherwise unexpected behavior.
The suggested changes add type checking to interceptors, and mirror this behavior to proxy processors so the return type is appropriately enforced.
Fixes #834
=> #834 Enforce type checking on method interceptors

hartshorn-core/src/main/java/org/dockbox/hartshorn/beans/BeanProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/beans/ContextBeanProvider.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/introspect/reflect/view/ContextParameterLoaderRule.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/parameter/ParameterLoader.java, hartshorn-core/src/main/java/org/dockbox/hartshorn/util/parameter/RuleBasedParameterLoader.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/beans/BeanObject.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/beans/BeanService.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/beans/BeanTests.java, hartshorn-core/src/test/java/org/dockbox/hartshorn/core/beans/TestBeanObserver.java, hartshorn-test-suite/src/main/java/org/dockbox/hartshorn/testsuite/HartshornLifecycleExtension.java
Currently it's only possible to get beans using a `Class` type and `String` ID. This is commonly abstracted to a `Key` instance, but this is not supported by the `BeanProvider` interface. This PR resolves this and appropriately handles the key lookup.
Additionally, this resolves #826 to ensure empty keys are handled correctly in parameter loaders.
Fixes #830
=> #830 Allow getting beans by `Key` value

build.gradle.kts
> CVE details: https://nvd.nist.gov/vuln/detail/CVE-2022-42889
> 
> Caused by transitive dependency on `org.apache.commons:commons-text:1.10.0` through `plume-util:options` in Checker Framework. As we only use the compile time plugin, and do not redistribute any of these dependencies this has been (safely) skipped in earlier pull requests (listed below).
> 
> - #835
> - #836
> - #838
> - #841
These changes resolve the use of the transitive dependency on `org.apache.commons:commons-text:1.10.0` through `plume-util:options` in Checker Framework. CF has recent releases which have updated the appropriate dependencies, which resolve the indirect use of `commons-text` in Hartshorn.
While not directly required to solve this CVE, these changes also lock the CF version to 3.27.0, instead of …
=> #844 Resolve CVE-2022-42889 through transitive dependency of Checker Framework
