core/src/main/kotlin/org/dockbox/darwin/core/command/context/CommandContext.kt
core/src/main/kotlin/org/dockbox/darwin/core/command/parse/AbstractArgumentParser.kt
core/src/main/kotlin/org/dockbox/darwin/core/command/parse/AbstractTypeArgumentParser.kt
core/src/main/kotlin/org/dockbox/darwin/core/i18n/I18N.kt
modules/src/main/java/org/dockbox/darwin/integrated/I18NModule.java

Player specific language switching

---

hartshorn-bootstrap/src/test/java/org/dockbox/hartshorn/api/PostBootstrapServiceProcessorTests.java

Fixes #387
**Describe the bug**
Since version 4.2.0 the `testProcessorAddsPostBootstrapActivations` test in `PostBootstrapServiceProcessorTests` has been disabled, as it required additional mocking of the bootstrap environment (now called `ApplicationContextAware` in the `ApplicationEnvironment`, which in turn is accessed through the `ApplicationContext`).
This test has been updated to mock the behavior and simply verify the method got called and the provided method is annotated with `@PostBootstrap`.
* Java version: OpenJDK 16.0.1

Update post-bootstrap activation tests

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java

#484 Add isArray and elementType methods to TypeContext

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/HartshornUtils.java

#486 Suppress continuous quality JAVA-W0243 on ternary operators

---

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/context/CommandDefinitionContextImpl.java

#480 Resolve invalid log level WARN at `CommandDefinitionContextImpl`

---

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/service/CommandServiceScanner.java

#481 Remove duplicate command method presence validation

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocatorImpl.java

Fixes #538
The `ComponentLocatorImpl` uses a static cache for present components. While this is fine when using a single Hartshorn instance, it will cause conflicts when multiple global states co-exist as activators may differ. This field should be converted to non-static. See:  
https://github.com/GuusLieben/Hartshorn/blob/6e7b2caa5a8d75a91e85b5dfb2bd55611febab80/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/services/ComponentLocatorImpl.java#L33
Converts the `cache` field to non-static and simplifies output logging to be more accurate when displaying these results.

#538 Remove static cache in component locator in favor of global state

---

hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/cli/SimpleCommandCLI.java

#551 Resolve non-blocking command CLI in async mode

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/ParameterContext.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/core/domain/Exceptional.java

Fixes #553
* Added `@Nullable` to appropriate methods in `Exceptional<T>`
* Added a `toArray` method in `HartshornUtils` that takes in a `TypeContext<T>` as a parameter

#553 QoL issues

---

hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java

In the `HttpWebServerInitializer`, the `MVCInitializer` is always called to activate MVC components even if the activator isn't present.
https://github.com/GuusLieben/Hartshorn/blob/9d606c504c5fdc9234cd1ad786733de75786d7d5/hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java#L86-L89
The registration of MVC contexts is however correctly filtered.
https://github.com/GuusLieben/Hartshorn/blob/9d606c504c5fdc9234cd1ad786733de75786d7d5/hartshorn-web/src/main/java/org/dockbox/hartshorn/web/HttpWebServerInitializer.java#L70-L77
This PR separates the initialization of MVC components based on the presence of the `UseMvc` activator.
Fixes #694

#694 Add activator filter to MVC initializer in HTTP Webserver initializer

---

build.gradle
hartshorn-core/src/main/java/org/dockbox/hartshorn/application/ApplicationPropertyHolder.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/application/EnvironmentDrivenApplicationConfigurator.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/StandardDelegatingApplicationContext.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/reflect/TypeContext.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/testsuite/HartshornFactoryTests.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationComponentPostProcessor.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationProviders.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationServicePreProcessor.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ContextPropertyValueLookup.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ValueLookup.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/annotations/Value.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/config/PropertyHolder.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/config/StandardPropertyHolder.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateJpaRepository.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/hibernate/HibernateRemoteImpl.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/jackson/JacksonObjectMapper.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/Address.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/ComponentWithUserValue.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/ConfigurationManagerTests.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/QueryRepositoryTests.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SqlServiceTest.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/User.java
hartshorn-data/src/test/java/org/dockbox/hartshorn/data/mapping/ObjectMappingTests.java

Currently it is only possible to provide primitive and basic types (Strings and Collections) through @Value fields. This is because the `ApplicationPropertyHolder` is unable to dynamically deserialize configuration states into complex types.
This PR moves the primary responsibility of complex configurations to Hartshorn Data, to allow it to use object mapping to easily deserialize to complex types. Standard configuration properties can still be requested through the `ApplicationPropertyHolder`, though all complex deserialization is handled by the `PropertyHolder`.
It is now possible to set and get complex types easily, as can be seen in the sample below:
```java
final PropertyHolder propertyHolder = this.applicationContext.get(PropertyHolder.class);
propertyHolder.set("user.name", "John …
```

#730 Allow for complex type deserialization in configuration provider

---

.github/workflows/hartshorn.yml
.github/workflows/owasp.yml
README.md
build.gradle

Updates the source JDK version to JDK 17 (LTS). CI configurations have been updated accordingly. Coming from JDK 16 this was a relatively minor change, 
Fixes #734

#734 Update source JDK to 17

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/DelegatingApplicationBindingFunction.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/inject/binding/BindingFunction.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/inject/binding/HierarchyBindingFunction.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/inject/processing/ProviderServicePreProcessor.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ApplicationContextTests.java

#751 Add priority support to binding functions

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/DelegatingApplicationContext.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/application/environment/ApplicationFSProviderImpl.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/FSProviderTests.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/ConfigurationServicePreProcessor.java
hartshorn-data/src/main/java/org/dockbox/hartshorn/data/FileSystemLookupStrategy.java

#759 Fix potential NPE on filesystem configuration lookup

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/DefaultProxyFactory.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/ProxyFactory.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ContextCarrierDelegationPostProcessor.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/proxy/processing/ProxyDelegationPostProcessor.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ContextCarrierDelegationTests.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/ContextCarrierService.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/IContextCarrierService.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/types/IDefaultContextCarrierService.java

#761 and #762 Fix proxy delegation issues

---

hartshorn-data/hartshorn-data-hibernate/hartshorn-data-hibernate.gradle
hartshorn-data/hartshorn-data-jackson/hartshorn-data-jackson.gradle
hartshorn-data/hartshorn-data.gradle
hartshorn-web/hartshorn-web-freemarker/hartshorn-web-freemarker.gradle
hartshorn-web/hartshorn-web-jetty/hartshorn-web-jetty.gradle

Separates artifact configurations for standard data and web implementations.
Fixes #772

#772 Separate data and web dependency concerns

---

hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/statement/ConstructorStatement.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/ast/statement/ParametricExecutableStatement.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/callable/virtual/VirtualClass.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/callable/virtual/VirtualFunction.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/interpreter/Interpreter.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/parser/Parser.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/semantic/Resolver.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/token/TokenType.java
hartshorn-hsl/src/main/java/org/dockbox/hartshorn/hsl/visitors/StatementVisitor.java
hartshorn-hsl/src/test/resources/class/class_extension.hsl
hartshorn-hsl/src/test/resources/class/constructor.hsl

The current way of handling constructors is by implementing the `init` function inside a class. While this is technically sufficient, it is not the clearest way of implementing constructors.
These changes replace the implicit `init` function with an explicit `constructor` statement, which otherwise follows the same specification. The constructor is internally identified by the unique identifier `<<init::$>>` where `$` represents the class name, for example `<<init::User>>`.
Fixes #783

#783 Replace virtual class init method with explicit constructor

---

hartshorn-commands/hartshorn-commands.gradle.kts
hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/CommandSource.java
hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/SystemSubject.java
hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/arguments/CustomParameterPattern.java
hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/arguments/PrefixedParameterPattern.java
hartshorn-commands/src/main/java/org/dockbox/hartshorn/commands/context/MethodCommandExecutorContext.java
hartshorn-commands/src/test/java/org/dockbox/hartshorn/commands/CommandConditionMatchingTests.java
hartshorn-commands/src/test/java/org/dockbox/hartshorn/commands/HashtagParameterPatternTests.java
hartshorn-commands/src/test/java/org/dockbox/hartshorn/commands/types/SampleCommand.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/component/condition/ProvidedParameterContext.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/Result.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/StringUtilities.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/ResultTests.java
hartshorn-core/src/test/java/org/dockbox/hartshorn/core/UtilitiesTests.java
hartshorn-i18n/src/main/java/org/dockbox/hartshorn/i18n/MessageTemplate.java

Builds on top of #806 by using the new `ProvidedParameterContext` to also perform condition matching for commands.
Fixes #805

#805 Condition matching for commands

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/application/context/ClasspathApplicationContext.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ProcessingOrder.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/component/processing/ProcessingPhase.java

#852 Improve phase logging of processor registration

---

hartshorn-core/src/main/java/org/dockbox/hartshorn/util/option/Attempt.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/option/none/FailedNone.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/option/none/SuccessNone.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/option/some/FailedSome.java
hartshorn-core/src/main/java/org/dockbox/hartshorn/util/option/some/SuccessSome.java
hartshorn-core/src/test/java/test/org/dockbox/hartshorn/core/OptionTests.java

#857 Support error-type specific error handling for `Attempt` instances
